import { StrategicInitiative, ExecutionEvidence } from './types';
import { Phase43StrategicRecommendation, StrategicPriority, StrategicRisk } from '../strategy/types';
import * as crypto from 'crypto';

export class InitiativeEngine {
  /**
   * Deterministically creates a StrategicInitiative from Phase 43 strategy items.
   */
  static createInitiative(params: {
    recommendation: Phase43StrategicRecommendation;
    priorities: StrategicPriority[];
    risks: StrategicRisk[];
    organizationId: string;
  }): StrategicInitiative {
    const { recommendation, priorities, risks, organizationId } = params;

    // Build execution evidence explicitly mapped to provenance
    const evidence: ExecutionEvidence[] = [];

    // Track provenance to priority
    // Use first addressed priority
    const targetPriorityId = recommendation.addressedPriorities[0];
    const priority = priorities.find(p => p.id === targetPriorityId);
    if (priority) {
      evidence.push({
        sourceType: 'PRIORITY',
        sourceId: priority.id,
        explanation: priority.description,
      });

      // Track provenance to underlying goals/metrics from the priority
      priority.sourceGoals.forEach(g => {
        evidence.push({
          sourceType: 'GOAL',
          sourceId: g,
          explanation: `Goal mapped via priority ${priority.id}`,
        });
      });
    }

    // Track provenance to risk
    const targetRiskId = recommendation.addressedRisks[0];
    const risk = risks.find(r => r.id === targetRiskId);
    if (risk) {
      evidence.push({
        sourceType: 'RISK',
        sourceId: risk.id,
        explanation: risk.description,
      });
    }

    evidence.push({
      sourceType: 'RECOMMENDATION',
      sourceId: recommendation.id,
      explanation: recommendation.title,
    });

    const category = priority ? priority.category : recommendation.category;

    return {
      id: `INIT-${crypto.randomUUID()}`,
      organizationId,
      title: `Initiative for: ${recommendation.title}`,
      description: recommendation.description,
      category,
      objective: recommendation.title,
      expectedOutcome: recommendation.description,
      priorityId: targetPriorityId || null,
      recommendationId: recommendation.id,
      relatedRiskIds: recommendation.addressedRisks || [],
      goalIds: priority?.sourceGoals || [],
      confidence: 'MEDIUM', // Assume medium or derive
      status: 'PROPOSED',
      evidence,
      executionPlan: null, // Will be generated by ExecutionPlanEngine
    };
  }
}
