import { prisma } from '../../lib/db';
import { GeminiProvider } from '../../ai/providers/gemini';
import { AIContext, ChatMessage } from '../../ai/providers/provider';
import * as crypto from 'crypto';

export interface RawAnomalyData {
  metricName: string;
  metricKey: string;
  currentValue: number;
  baselineValue: number;
  changePercentage: number;
  eventType: string; // ANOMALY | HEALTH_CHANGE | INTEGRATION_FAILURE
  severity: 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  description: string;
  sourceTable: string;
  sourceRecordId?: string;
  domain: string;
}

export class InsightGenerator {
  static async createExecutiveEvent(organizationId: string, anomaly: RawAnomalyData) {
    const period = new Date().toISOString().substring(0, 10);
    const fingerprintString = `${organizationId}:${anomaly.metricKey}:${period}:${anomaly.eventType}:${anomaly.severity}`;
    const fingerprint = crypto.createHash('sha256').update(fingerprintString).digest('hex');

    const existing = await prisma.executiveEvent.findFirst({
      where: { fingerprint }
    });

    if (existing) {
      console.log(`[InsightGenerator] ExecutiveEvent already exists for fingerprint: ${fingerprint}`);
      return existing;
    }

    const facts = JSON.stringify([
      `Metric ${anomaly.metricName} changed by ${anomaly.changePercentage}%`,
      `Current value is ${anomaly.currentValue}, baseline was ${anomaly.baselineValue}`
    ]);

    const event = await prisma.executiveEvent.create({
      data: {
        organizationId,
        eventType: anomaly.eventType,
        domain: anomaly.domain,
        severity: anomaly.severity,
        title: anomaly.description,
        summary: `Detected ${anomaly.severity} change in ${anomaly.metricName}.`,
        sourceTable: anomaly.sourceTable,
        sourceRecordId: anomaly.sourceRecordId,
        facts,
        occurredAt: new Date(),
        fingerprint,
        processed: false
      }
    });

    return event;
  }

  static async processEventToRecommendation(organizationId: string, eventId: string) {
    const event = await prisma.executiveEvent.findUnique({ where: { id: eventId } });
    if (!event || event.processed) return null;

    let executiveSummary = "Explanation could not be generated.";
    let title = event.title;
    let expectedImpact = "Unknown";
    let actionProposal = null;

    try {
      const provider = new GeminiProvider();
      const context: AIContext = { organizationId, userId: 'system', role: 'system' };
      
      const messages: ChatMessage[] = [
        {
          role: 'system',
          content: `[SYSTEM: VERIFIED BUSINESS INTELLIGENCE LAYER]
You are generating a business insight and recommendation.

VERIFIED EVENT:
Title: ${event.title}
Severity: ${event.severity}
Facts: ${event.facts}

RULES:
1. Do not invent missing values or fabricate causes.
2. Generate a JSON object with: 
   "title" (a concise 5-word title), 
   "executiveSummary" (a brief 2-3 sentence explanation), 
   "expectedImpact" (a short sentence describing what happens if unaddressed),
   "actionProposal" (Optional. A JSON object with "actionName", "actionArgs", "humanDescription" representing a proposed action).
3. If there is insufficient evidence for a cause, say "Cause cannot be determined."
4. Output ONLY valid JSON.`
        }
      ];

      const aiResponse = await provider.generateCompletion(context, messages);
      const content = aiResponse.message.content.trim();
      
      try {
        const jsonStr = content.replace(/```json/g, '').replace(/```/g, '').trim();
        const parsed = JSON.parse(jsonStr);
        if (parsed.title) title = parsed.title;
        if (parsed.executiveSummary) executiveSummary = parsed.executiveSummary;
        if (parsed.expectedImpact) expectedImpact = parsed.expectedImpact;
        if (parsed.actionProposal) actionProposal = parsed.actionProposal;
      } catch (parseError) {
        console.error("[InsightGenerator] Failed to parse AI JSON response.", parseError);
        executiveSummary = content; 
      }
    } catch (error) {
      console.error("[InsightGenerator] LLM failed to generate recommendation.", error);
      executiveSummary = "AI explanation temporarily unavailable.";
    }

    let pendingActionId = null;

    // Governance link: If AI proposes an actionable measure, stage it as a human-gated PendingAction
    if (actionProposal && actionProposal.actionName) {
      const pendingAction = await prisma.pendingAction.create({
        data: {
          organizationId,
          requestingUserId: 'system', // Generated by system
          conversationId: 'system-generated', // Fake conversation id for background tasks
          actionType: 'SYSTEM_PROPOSAL',
          actionName: actionProposal.actionName,
          actionArgs: JSON.stringify(actionProposal.actionArgs || {}),
          humanDescription: actionProposal.humanDescription || `System proposed action: ${actionProposal.actionName}`,
          riskLevel: 'MEDIUM',
          idempotencyKey: crypto.randomUUID(),
          status: 'WAITING',
          expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days
        }
      });
      pendingActionId = pendingAction.id;
    }

    const priorityScore = event.severity === 'CRITICAL' ? 90 : (event.severity === 'HIGH' ? 70 : 40);

    const recommendation = await prisma.executiveRecommendation.create({
      data: {
        organizationId,
        domain: event.domain,
        priorityScore,
        priorityLevel: event.severity === 'CRITICAL' ? 'CRITICAL' : (event.severity === 'HIGH' ? 'HIGH' : 'MEDIUM'),
        title,
        executiveSummary,
        reasoning: event.facts,
        expectedImpact,
        confidence: 'MEDIUM',
        actionProposal: actionProposal ? JSON.stringify(actionProposal) : 'null',
        status: 'PROPOSED',
        pendingActionId
      }
    });

    await prisma.executiveEvent.update({
      where: { id: event.id },
      data: { processed: true, processedAt: new Date() }
    });

    return recommendation;
  }
}
